### ISSUE TITLE
iOS build error with Cordova 6.0.0

### ISSUE THREAD

**Issue by sdbroscious** [kant2002/cordova-plugin-screen-orientation#1]
I'm trying to upgrade a Cordova project from 5.1.1 to 6.0.0. Part of this effort involves replacing the net.yoik.cordova.plugins.screenorientation with cordoba-plugin-screen-orientation, per the directive to use npm plugins.

The problem I'm having is that I cannot build the project once I add the plugin. Here's the console output for 'cordova build iOS':

```
** BUILD FAILED **


The following build commands failed:
    CompileC build/GAI\ app.build/Debug-iphonesimulator/GAI\ app.build/Objects-normal/i386/YoikScreenOrientation.o GAI\ app/Plugins/cordova-plugin-screen-orientation/YoikScreenOrientation.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
(1 failure)
ERROR building one of the platforms: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/bob/Documents/workspace_cordova/mobileapp/platforms/ios/cordova/build-debug.xcconfig,-project,GAI app.xcodeproj,ARCHS=i386,-target,GAI app,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/bob/Documents/workspace_cordova/mobileapp/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/bob/Documents/workspace_cordova/mobileapp/platforms/ios/build/sharedpch
You may not have the required environment or OS to build this project
Error: Error code 65 for command: xcodebuild with args: -xcconfig,/Users/bob/Documents/workspace_cordova/mobileapp/platforms/ios/cordova/build-debug.xcconfig,-project,GAI app.xcodeproj,ARCHS=i386,-target,GAI app,-configuration,Debug,-sdk,iphonesimulator,build,VALID_ARCHS=i386,CONFIGURATION_BUILD_DIR=/Users/bob/Documents/workspace_cordova/mobileapp/platforms/ios/build/emulator,SHARED_PRECOMPS_DIR=/Users/bob/Documents/workspace_cordova/mobileapp/platforms/ios/build/sharedpch
```

I've opened up Xcode (7.2.1) to see what more I could see and I do see this build error in the project:

`/Users/bob/Documents/workspace_cordova/mobileTrucking (trunk)/platforms/ios/GAI Trucking/Plugins/cordova-plugin-screen-orientation/YoikScreenOrientation.h:26:9: 'Cordova/CDVShared.h' file not found`

YoikScreenOrientation.h imports Cordova/CDVShared.h. I've scoured the project and cannot find the CDVShared.h file anywhere. This looks like a core Cordova file but I'm not clear on how it gets into the project. Is it a file that's no longer included with 6.0.0?

Any advice or assistance would be appreciated.

**Comment by kant2002** [comment]
@sdbroscious I didn't try that plugin on Corodova 6.0 yet, but still something not clear for me.
Where `YoikScreenOrientation.h` comes from?

**Comment by sdbroscious** [comment]
That's a great question...I'm going to look at that and when I find the answer, I'll report back. Thanks!

**Comment by sdbroscious** [comment]
Turns out there are 2 cordova-plugin-screen orientation plugins: yours and [the one Cordova grabs via NPM](https://github.com/gbenvenuti/cordova-plugin-screen-orientation). The other one has the YoikScreenOrientation files and the import of CDVShared.h that's no longer in Cordova.

Far as I can tell, this is a non-issue for you. Sorry for the confusion.
